# Generated by Django 3.1.14 on 2026-06-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0044_auto_20250606_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='isLidar',
            field=models.BooleanField(default=False),
        ),
    ]
